# docker-compose.yml

version: '3.8'
services:

  postgres:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - '5432:5432'

volumes:
  postgres: